name: build
on: [push, pull_request,workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [RelWithDebInfo]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Workaround for windows-2022 and cmake 3.25.0
      if: runner.os == 'Windows'
      shell: bash
      run: mv C:/Strawberry/ C:/fuckup.no/
    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          sudo apt-get update -qq
          sudo apt-get install -y \
            libx11-dev libxcursor-dev libxi-dev
        fi
    #- name: Download GitHub Release
      # You may pin to the exact commit or the version.
      # uses: Legion2/download-release-action@68df3d242858e28a7e6d8b9838a3e6730cdfc422
      #uses: Legion2/download-release-action@v2.1.0
      #with:
        # The repository from where to download the files. Given as <user>/<repository>
        #repository: aseprite/skia
        # The version tag of the release
        #tag: m102-861e4743af
        # The file which should be downloaded.
        #file: Skia-Windows-Release-x64.zip
        # download directory
        #path: ./
    - name: Unzip SKIA
      if: runner.os == 'Windows'
      run: |
        #curl -o SKIAa.zip https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
        unzip Skia-Windows-Release-x64.zip -d libSKIA

    - name: Cache third-party
      uses: actions/cache@v3
      with:
        key: 3pt-b
        restore-keys: 3pt-b
        path: build/third_party/*/*.obj
    - name: Cache third-party r
      uses: actions/cache@v3
      with:
        key: 3pt
        path: third_party/*/*.obj
    - name: Cache laf
      uses: actions/cache@v3
      with:
        key: laf-b
        restore-keys: laf-b
        path: build/laf/*/*.obj
    - name: Cache laf r
      uses: actions/cache@v3
      with:
        key: laf
        path: laf/*/*.obj
    - name: Cache objs
      uses: actions/cache@v3
      with:
        key: arc-cmobj
        path: ./*/src/app/CMakeFiles/*/*.obj
    - name: Cache objs2
      uses: actions/cache@v3
      with:
        key: opbj-exes-cache
        restore-key: obj2
        path: |
          src/app/CMakeFiles/*/*.obj
          src/app/CMakeFiles/app-lib.dir/script/*.obj
          build/CMakeCache.txt
          CMakeCache.txt
          src/CMakeCache.txt
          third_party/IXWebSocket/CMakeFiles/ixwebsocket.dir/ixwebsocket/*.cpp.obj
          third_party/libarchive/libarchive/CMakeFiles/archive_static.dir/*.obj
          third_party/jpeg/CMakeFiles/jpeg.dir/*.obj
          third_party/*/*.exe
          lib/
          src/doc/CMakeFiles/doc-lib.dir/*.obj
          src/ui/CMakeFiles/ui-lib.dir/*.cpp.obj
    - name: Generating Makefiles
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          export enable_ccache=off
        else
          export enable_ccache=on
        fi
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_TESTS=ON \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./libSKIA \
          -DSKIA_LIBRARY_DIR=./libSKIA/out/Release-x64 \
          -DSKIA_LIBRARY=./libSKIA/out/Release-x64/skia.lib \
          -DENABLE_CCACHE=$enable_ccache

    - name: Compiling
      shell: bash
      run: |
        cd build && ninja -j 4
    - name: artifacts al build/
      uses: actions/upload-artifact@v3
      with:
          name: build_outs
          path: build/bin/*asep*exe
    - name: artifact build/data dir
      uses: actions/upload-artifact@v3
      with:
          name: prog_data
          path: build/bin/data/*

